#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"

if [ -z "$branch" ] || [ "$branch" = "HEAD" ]; then
  exit 0
fi

printf "[auto-push] Pushing %s to origin...\n" "$branch"
git push origin "$branch"
